image:
  repository: postgres
  tag: latest
  pullPolicy: IfNotPresent

postgres:
  user: admin
  password: admin

service:
  port: 5432

persistence:
  enabled: true
  size: 1Gi
  storageClass: "standard"