apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-loki-svc
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3100
      targetPort: 3100
  selector:
    app: {{ .Release.Name }}-loki