apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    uid: P8E80F9AEF21F6940
    url: http://loki:3100
    
  - name: Tempo
    type: tempo
    url: http://tempo:3200
    jsonData:
      streamingEnabled:
        metrics: true
        search: true
      tracesToLogsV2:
        customQuery: false
        datasourceUid: P8E80F9AEF21F6940
        filterBySpanID: true
        filterByTraceID: true
        spanStartTimeShift: "-5s"
      tracesToMetrics:
        datasourceUid: PBFA97CFB590B2093
        spanStartTimeShift: "-5s"
      nodeGraph:
        enabled: true
      search:
        filters:
        - id: service-name
          operator: "="
          scope: resource
          tag: service.name
        - id: span-name
          operator: "="
          scope: span
          tag: name
      serviceMap:
        datasourceUid: PBFA97CFB590B2093
      traceQuery:
        spanStartTimeShift: "-100ms"
        timeShiftEnabled: true