{
 "title": "App Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Services",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "All logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"backend|frontend|nginx-rp\"} |= ``"
    }
   ]
  },
  {
   "title": "Details for $Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "Services",
   "collapsed": true,
   "panels": [
    {
     "title": "Logs for $Services",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{service_name=\"$Services\"} |= ``"
      }
     ]
    },
    {
     "title": "Traces for $Services",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "filters": [
        {
         "id": "84b55b67",
         "operator": "=",
         "scope": "span",
         "value": []
        },
        {
         "id": "service-name",
         "operator": "=",
         "scope": "resource",
         "tag": "service.name",
         "value": [ "backend" ],
         "valueType": "string"
        },
        {
         "id": "span-name",
         "operator": "=",
         "scope": "span",
         "tag": "name",
         "value": [],
         "valueType": "string"
        }
       ],
       "limit": 20,
       "metricsQueryType": "range",
       "query": "{resource.service.name=\"$Services\"}",
       "tableType": "traces"
      }
     ]
    },
    {
     "title": "Metrics for $Services",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "{exported_job=\"$Services\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}