apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-config
  namespace: {{ .Values.global.namespace }}
data:
  datasources.yaml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        uid: PBFA97CFB590B2093
        url: http://{{ .Release.Name }}-prometheus-svc:9090
        isDefault: true

      - name: Loki
        type: loki
        uid: P8E80F9AEF21F6940
        url: http://{{ .Release.Name }}-loki-svc:3100
        
      - name: Tempo
        type: tempo
        url: http://{{ .Release.Name }}-tempo-svc:3200
        jsonData:
          streamingEnabled:
            metrics: true
            search: true
          tracesToLogsV2:
            customQuery: false
            datasourceUid: P8E80F9AEF21F6940
            filterBySpanID: true
            filterByTraceID: true
            spanStartTimeShift: "-5s"
          tracesToMetrics:
            datasourceUid: PBFA97CFB590B2093
            spanStartTimeShift: "-5s"
          nodeGraph:
            enabled: true
          search:
            filters:
            - id: service-name
              operator: "="
              scope: resource
              tag: service.name
            - id: span-name
              operator: "="
              scope: span
              tag: name
          serviceMap:
            datasourceUid: PBFA97CFB590B2093
          traceQuery:
            spanStartTimeShift: "-100ms"
            timeShiftEnabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-config-dashboard
  namespace: {{ .Values.global.namespace }}
data:
  default.yaml: |
    apiVersion: 1

    providers:
      - name: Default
        folder: Services
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-dashboard
  namespace: {{ .Values.global.namespace }}
data:
  app-dashboard.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 1,
      "links": [],
      "panels": [
        {
          "datasource": {
            "type": "loki",
            "uid": "P8E80F9AEF21F6940"
          },
          "fieldConfig": {
            "defaults": {},
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 5,
          "options": {
            "dedupStrategy": "none",
            "enableInfiniteScrolling": false,
            "enableLogDetails": true,
            "prettifyLogMessage": false,
            "showCommonLabels": false,
            "showLabels": false,
            "showTime": true,
            "sortOrder": "Descending",
            "wrapLogMessage": false
          },
          "pluginVersion": "12.0.1+security-01",
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "P8E80F9AEF21F6940"
              },
              "direction": "backward",
              "editorMode": "builder",
              "expr": "{service_name=~\"backend|frontend|nginx-rp\"} |= ``",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "All logs",
          "type": "logs"
        },
        {
          "collapsed": true,
          "gridPos": {
            "h": 1,
            "w": 24,
            "x": 0,
            "y": 8
          },
          "id": 2,
          "panels": [
            {
              "datasource": {
                "type": "loki",
                "uid": "P8E80F9AEF21F6940"
              },
              "fieldConfig": {
                "defaults": {},
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 0,
                "y": 1
              },
              "id": 1,
              "options": {
                "dedupStrategy": "none",
                "enableInfiniteScrolling": false,
                "enableLogDetails": true,
                "prettifyLogMessage": false,
                "showCommonLabels": false,
                "showLabels": false,
                "showTime": true,
                "sortOrder": "Descending",
                "wrapLogMessage": false
              },
              "pluginVersion": "12.0.1+security-01",
              "targets": [
                {
                  "datasource": {
                    "type": "loki",
                    "uid": "P8E80F9AEF21F6940"
                  },
                  "direction": "backward",
                  "editorMode": "builder",
                  "expr": "{service_name=\"$Services\"} |= ``",
                  "queryType": "range",
                  "refId": "A"
                }
              ],
              "title": "Logs for $Services",
              "type": "logs"
            },
            {
              "datasource": {
                "type": "tempo",
                "uid": "P214B5B846CF3925F"
              },
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisBorderShow": false,
                    "axisCenteredZero": false,
                    "axisColorMode": "text",
                    "axisLabel": "",
                    "axisPlacement": "auto",
                    "barAlignment": 0,
                    "barWidthFactor": 0.6,
                    "drawStyle": "bars",
                    "fillOpacity": 100,
                    "gradientMode": "hue",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "insertNulls": false,
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "auto",
                    "spanNulls": false,
                    "stacking": {
                      "group": "A",
                      "mode": "normal"
                    },
                    "thresholdsStyle": {
                      "mode": "off"
                    }
                  },
                  "links": [
                    {
                      "oneClick": false,
                      "targetBlank": true,
                      "title": "Click for Traces",
                      "url": "/explore?left={\"datasource\":\"Tempo\",\"queries\":[{\"query\":\"${__data.fields[1]}\"}],\"range\":{\"from\":\"${__from}\",\"to\":\"${__to}\"}}\n"
                    }
                  ],
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green"
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  }
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 12,
                "y": 1
              },
              "id": 3,
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "hidden",
                  "placement": "right",
                  "showLegend": false
                },
                "tooltip": {
                  "hideZeros": false,
                  "mode": "single",
                  "sort": "none"
                }
              },
              "pluginVersion": "12.0.1+security-01",
              "targets": [
                {
                  "datasource": {
                    "type": "tempo",
                    "uid": "P214B5B846CF3925F"
                  },
                  "filters": [
                    {
                      "id": "84b55b67",
                      "operator": "=",
                      "scope": "span",
                      "value": []
                    },
                    {
                      "id": "service-name",
                      "operator": "=",
                      "scope": "resource",
                      "tag": "service.name",
                      "value": [
                        "backend"
                      ],
                      "valueType": "string"
                    },
                    {
                      "id": "span-name",
                      "operator": "=",
                      "scope": "span",
                      "tag": "name",
                      "value": [],
                      "valueType": "string"
                    }
                  ],
                  "limit": 20,
                  "metricsQueryType": "range",
                  "query": "{resource.service.name=\"$Services\"}",
                  "queryType": "traceql",
                  "refId": "A",
                  "tableType": "traces"
                }
              ],
              "title": "Traces for $Services",
              "type": "timeseries"
            },
            {
              "datasource": {
                "type": "prometheus",
                "uid": "PBFA97CFB590B2093"
              },
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisBorderShow": false,
                    "axisCenteredZero": false,
                    "axisColorMode": "text",
                    "axisLabel": "",
                    "axisPlacement": "auto",
                    "barAlignment": 0,
                    "barWidthFactor": 0.6,
                    "drawStyle": "line",
                    "fillOpacity": 0,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "insertNulls": false,
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "auto",
                    "spanNulls": false,
                    "stacking": {
                      "group": "A",
                      "mode": "none"
                    },
                    "thresholdsStyle": {
                      "mode": "off"
                    }
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green"
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  }
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 0,
                "y": 9
              },
              "id": 4,
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "list",
                  "placement": "bottom",
                  "showLegend": true
                },
                "tooltip": {
                  "hideZeros": false,
                  "mode": "single",
                  "sort": "none"
                }
              },
              "pluginVersion": "12.0.1+security-01",
              "targets": [
                {
                  "datasource": {
                    "type": "prometheus",
                    "uid": "PBFA97CFB590B2093"
                  },
                  "disableTextWrap": false,
                  "editorMode": "builder",
                  "expr": "{exported_job=\"$Services\"}",
                  "format": "time_series",
                  "fullMetaSearch": false,
                  "hide": false,
                  "includeNullMetadata": true,
                  "instant": false,
                  "legendFormat": "__auto",
                  "range": true,
                  "refId": "A",
                  "useBackend": true
                }
              ],
              "title": "Metrics for $Services",
              "type": "timeseries"
            }
          ],
          "repeat": "Services",
          "title": "Details for $Services",
          "type": "row"
        }
      ],
      "preload": false,
      "schemaVersion": 41,
      "tags": [],
      "templating": {
        "list": [
          {
            "current": {
              "text": [
                "frontend",
                "backend",
                "nginx-rp"
              ],
              "value": [
                "frontend",
                "backend",
                "nginx-rp"
              ]
            },
            "datasource": {
              "type": "loki",
              "uid": "P8E80F9AEF21F6940"
            },
            "definition": "",
            "includeAll": true,
            "multi": true,
            "name": "Services",
            "options": [],
            "query": {
              "label": "service_name",
              "refId": "LokiVariableQueryEditor-VariableQuery",
              "stream": "",
              "type": 1
            },
            "refresh": 1,
            "regex": "",
            "type": "query"
          }
        ]
      },
      "time": {
        "from": "now-3h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "browser",
      "title": "App Dashboard",
      "uid": "e6450ace-e56f-4d21-855d-c497b6a5b9c3",
      "version": 1
    }
