apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana-svc
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-grafana