apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tempo-svc
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: otlp-http
      port: 14268
      targetPort: 14268
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: zipkin
      port: 9411
      targetPort: 9411
    - name: http
      port: 3200
      targetPort: 3200
  selector:
    app: {{ .Release.Name }}-tempo