apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
  namespace: {{ .Values.global.namespace }}
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['{{ .Release.Name }}-otel-collector-svc:9464']
        scrape_interval: 5s