# /tmp/otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  postgresql:
    endpoint: "my-postgres:5432"
    transport: tcp
    username: admin
    password: admin
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          static_configs:
            - targets: ['localhost:9464']

  filelog:
    include: ["/logs/nginx/*.log"]

exporters:
  otlp:
    endpoint: http://tempo:4317
    tls:
      insecure: true
  otlphttp:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:9464"
processors:
  batch: {}
  resource:
    attributes:
      - action: insert
        key: service.name
        value: nginx-rp
        
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [otlphttp]
      processors: [batch]
    logs/nginx:
      receivers: [filelog]
      exporters: [otlphttp/loki]
      processors: [resource]