apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-svc
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
  selector:
    app: {{ .Release.Name }}-redis
