apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-otel-collector-config
  namespace: {{ .Values.global.namespace }}
data:
  otel-collector-config.yaml: |
    # /tmp/otel-collector-config.yaml
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      postgresql:
        endpoint: "{{ .Release.Name }}-postgres-svc:5432"
        transport: tcp
        username: admin
        password: admin
    exporters:
      # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
      otlp:
        endpoint: http://{{ .Release.Name }}-tempo-svc:4317
        tls:
          insecure: true
      otlphttp:
        endpoint: http://{{ .Release.Name }}-loki-svc:3100/otlp
        tls:
          insecure: true

      otlphttp/loki:
        endpoint: http://{{ .Release.Name }}-loki-svc:3100/otlp
        tls:
          insecure: true
      debug:
        verbosity: detailed
      prometheus:
        endpoint: "0.0.0.0:9464"
    processors:
      batch: {}
      resource:
        attributes:
          - action: insert
            key: service.name
            value: nginx-rp      
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
          processors: [batch]
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
          processors: [batch]
        logs:
          receivers: [otlp]
          exporters: [otlphttp]
          processors: [batch]
        # logs/nginx:
        #   receivers: [filelog]
        #   exporters: [otlphttp]
        #   processors: [batch]