apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-otel-collector
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-otel-collector
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-otel-collector
    spec:
      containers:
        - name: otel-collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--config=/etc/otel-collector-config.yaml"]
          ports:
            - containerPort: {{ .Values.service.ports.otlpHttp }}
            - containerPort: {{ .Values.service.ports.otlpGrpc }}
            - containerPort: {{ .Values.service.ports.promExporter1 }}
            - containerPort: {{ .Values.service.ports.promExporter2 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-otel-collector-config