apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-otel-collector-svc
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: otlp-http
      port: {{ .Values.service.ports.otlpHttp }}
      targetPort: {{ .Values.service.ports.otlpHttp }}
    - name: otlp-grpc
      port: {{ .Values.service.ports.otlpGrpc }}
      targetPort: {{ .Values.service.ports.otlpGrpc }}
    - name: prom-exp1
      port: {{ .Values.service.ports.promExporter1 }}
      targetPort: {{ .Values.service.ports.promExporter1 }}
    - name: prom-exp2
      port: {{ .Values.service.ports.promExporter2 }}
      targetPort: {{ .Values.service.ports.promExporter2 }}
  selector:
    app: {{ .Release.Name }}-otel-collector