image:
  repository: grafana/grafana
  tag: latest
  pullPolicy: IfNotPresent

env:
  adminUserSecretName: grafana-admin-secret
  adminUserKey: GF_SECURITY_ADMIN_USER
  adminPasswordKey: GF_SECURITY_ADMIN_PASSWORD

service:
  port: 3000

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""