apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env.adminUserSecretName }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  username: YWRtaW4=     # base64 for "admin"
  password: YWRtaW4=     # base64 for "admin"