apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-svc
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: {{ .Release.Name }}-frontend